server:
  port: ${PORT}

spring:
  application:
    name: collabond

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/collabond
    username: ${MYSQL_ID}
    password: ${MYSQL_PW}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PW}
            redirect-uri: http://localhost:${PORT}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: http://localhost:${PORT}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_PW}
            redirect-uri: http://localhost:${PORT}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

logging:
  level:
    org.springframework.security: TRACE

custom:
  file:
    path: ${FILE_PATH}/collabond/images/  # ?? ?? ??
  cors:
    allowed-origin: http://localhost:3000
  jwt:
    token-validity-time: # 초 단위
      access: 600 # 10분
      refresh: 604800 # 7일
    secret: 76a6057b59bd44c7a87bbaa0576dae0376a6057b59bd44c7a87bbaa0576dae0376a6057b59bd44c7a87bbaa0576dae03
    redirect-login-success: ${custom.cors.allowed-origin}/auth/callback
  mail:
    subject:
      apply-received: '[Collabond] 새로운 지원자가 있습니다!'